version: '3'
services:
  gitslackbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
      - 3004:3004
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    restart: always
volumes:
  logs: